name: Deploy to Chrome Web Store

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build extension
        run: pnpm build

      - name: Create extension package
        run: |
          mkdir -p chrome-extension
          cp manifest.json chrome-extension/
          cp background.js chrome-extension/
          cp content.js chrome-extension/
          cp LICENSE chrome-extension/
          cp README.md chrome-extension/
          
          cd chrome-extension
          zip -r ../chrome-extension.zip *
          cd ..

      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: chrome-extension.zip
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          # Optionally, you can control publishing:
          # publish: true # Set to false to upload as draft

      - name: Upload Status Summary
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "### ✅ Chrome Web Store Deployment Successful!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "The extension has been uploaded to Chrome Web Store." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Note:** The extension will be reviewed by Google before being published." >> $GITHUB_STEP_SUMMARY
          else
            echo "### ❌ Chrome Web Store Deployment Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please check the logs for more details." >> $GITHUB_STEP_SUMMARY
          fi